# Generated by Django 2.1.3 on 2018-11-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("tag", models.CharField(max_length=20)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Toast",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("toast", models.TextField(max_length=500)),
                (
                    "explicit",
                    models.BooleanField(
                        default=False, verbose_name="Explicit Language"
                    ),
                ),
                (
                    "disabled",
                    models.BooleanField(default=False, verbose_name="Disabled"),
                ),
                (
                    "numUsed",
                    models.IntegerField(default=0, verbose_name="Number of times used"),
                ),
                ("tags", models.ManyToManyField(to="chest.Tag")),
            ],
            options={"abstract": False},
        ),
    ]
