# Generated by Django 2.1.3 on 2018-11-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toast",
            name="tags",
            field=models.ManyToManyField(related_name="toasts", to="chest.Tag"),
        ),
    ]
